name: Deploy AWS Control Tower Landing

on:
  push:
    branches: [ "main" ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  AWS_ACCOUNT_ID: 411634473249

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v5.1.0
      with:
        role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/GitHubActionsDeployRole
        aws-region: ${{ env.AWS_REGION }}

    - name: Validate Landing Zone Template
      run: |
        aws cloudformation validate-template \
        --template-body file://templates/landing-zone.yaml \
        --output json \
        --region us-east-1

    - name: Deploy Landing Zone Template
      run: |
        aws cloudformation deploy \
        --stack-name landing-zone-stack \
        --template-file templates/landing-zone.yaml \
        --output json \
        --region us-east-1  


